# Generated by Django 3.1.5 on 2021-02-03 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='realtor',
            name='name',
        ),
        migrations.AddField(
            model_name='realtor',
            name='user_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
